resources:
  Dbp\Relay\BaseCourseBundle\Entity\Course:
    types: ['https://schema.org/Course']
    shortName: 'BaseCourse'
    normalizationContext:
      groups: ['BaseCourse:output', 'LocalData:output']
      jsonld_embed_context: true
    operations:
      ApiPlatform\Metadata\Get:
        provider: Dbp\Relay\BaseCourseBundle\DataProvider\CourseDataProvider
        uriTemplate: '/base/courses/{identifier}'
        openapiContext:
          tags: ["BaseCourse"]
          parameters:
            - name: includeLocal
              in: query
              description: 'Local data attributes to include'
              type: string

      ApiPlatform\Metadata\GetCollection:
        provider: Dbp\Relay\BaseCourseBundle\DataProvider\CourseDataProvider
        uriTemplate: '/base/courses'
        openapiContext:
          tags: ['BaseCourse']
          parameters:
            - name: search
              in: query
              description: "Search filter (partial, case-insensitive text search on 'name' attribute)"
              required: false
              type: string
            - name: includeLocal
              in: query
              description: 'Local data attributes to include'
              type: string

    properties:
      identifier:
        identifier: true
      name:
        iri: 'https://schema.org/name'
      type:
      localData:
        iri: 'https://schema.org/additionalProperty'
