services:
  Dbp\Relay\CourseBundle\Controller\:
    resource: '../../Controller'
    autoconfigure: true
    autowire: true

  Dbp\Relay\CourseBundle\DataProvider\:
    resource: '../../DataProvider'
    autowire: true
    autoconfigure: true

  Dbp\Relay\CourseBundle\Service\DummyCourseProvider:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CourseBundle\API\CourseProviderInterface:
    '@Dbp\Relay\CourseBundle\Service\DummyCourseProvider'
