services:
  Dbp\Relay\BaseCourseBundle\Controller\:
    resource: '../../Controller'
    autoconfigure: true
    autowire: true

  Dbp\Relay\BaseCourseBundle\DataProvider\:
    resource: '../../DataProvider'
    autowire: true
    autoconfigure: true

  Dbp\Relay\BaseCourseBundle\Service\DummyCourseProvider:
    autowire: true
    autoconfigure: true

  Dbp\Relay\BaseCourseBundle\API\CourseProviderInterface:
    '@Dbp\Relay\BaseCourseBundle\Service\DummyCourseProvider'
