services:
  Dbp\Relay\BaseCourseBundle\Controller\GetAttendeesByCourse:
    autoconfigure: true
    autowire: true

  Dbp\Relay\BaseCourseBundle\DataProvider\CourseDataProvider:
    autowire: true
    autoconfigure: true

  Dbp\Relay\BaseCourseBundle\Service\DummyCourseProvider:
    autowire: true
    autoconfigure: true

  Dbp\Relay\BaseCourseBundle\API\CourseProviderInterface:
    '@Dbp\Relay\BaseCourseBundle\Service\DummyCourseProvider'
